
name: $(Date:yyyyMMdd).$(Rev:r)

trigger:
  batch: true
  branches:
    include: [ "*" ]
  paths:
    exclude: [ "README.md" ]

jobs:
  - job: image
    displayName: "build image"
    pool:
      vmImage: "ubuntu-latest"
    workspace:
      clean: all
    timeoutInMinutes: 120

    steps:
    - bash: 'sudo -E ./00-install-deps.sh'
      displayName: '00-install-deps'

    - bash: 'sudo -E ./10-env.sh'
      displayName: '10-env'

    - bash: 'sudo -E ./20-kernel-initramfs.sh'
      displayName: '20-kernel-initramfs'

    - bash: 'sudo -E ./30-rootfs.sh'
      displayName: '30-rootfs'

    - bash: 'sudo -E ./40-image.sh'
      displayName: '40-image'

    - bash: 'sudo -E ./50-pack.sh'
      displayName: '50-pack'

    - bash: |
            cp -r build/*.{tar.gz,squashfs,qcow2,vmdk,vhdx} build/boot build/packages.txt ${BUILD_ARTIFACTSTAGINGDIRECTORY}
      displayName: 'copy artifact'

    - task: PublishBuildArtifacts@1
      displayName: 'publish artifact'
      inputs:
        artifactName: 'image'
